name: 又拍云插件
identification: notadd/cloud/upyun
description: 又拍云管理插件。
author:
    - Allen
    - 674397601@qq.com
version: 0.1.0
provider: Notadd\Cloud\Extension
assets:
    scripts:
        - assets/extensions/notadd/cloud/js/extension.min.js
    stylesheets:
        - assets/extensions/notadd/cloud/css/extension.min.css
csrf:
    - 'api/cloud*'
events:
    subscribes:
        - Notadd\Cloud\Listeners\RouteRegister
migrations:
    - databases/migrations
publishes:
    assets/extensions/notadd/cloud: resources/mixes/administration/dist/assets/extensions/notadd/cloud
